### ISSUE TITLE
Cassandra specs failing

### ISSUE THREAD

**Issue by meatballhat** [travis-ci/packer-templates#589]
The specs for Cassandra are currently failing on Xenial, e.g.: https://travis-ci.org/travis-infrastructure/packer-build/jobs/335257786#L5474-L5479

![](https://i.imgur.com/LZ4F1Hs.png)

**Comment by meatballhat** [comment]
This is showing up in `/var/log/cassandra/debug.log` when attempting to bring up `cassandra` during a packer build:

```
ERROR [main] 2018-01-30 20:20:12,276 CassandraDaemon.java:747 - Exception encountered during startup
java.lang.AbstractMethodError: org.apache.cassandra.utils.JMXServerUtils$Exporter.exportObject(Ljava/rmi/Remote;ILjava/rmi/server/RMIClientSocketFactory;Ljava/rmi/server/RMIServerSocketFactory;Lsun/misc/ObjectInputFilter;)Ljava/rmi/Remote;
        at javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:150) ~[na:1.8.0_161]
        at javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:135) ~[na:1.8.0_161]
        at javax.management.remote.rmi.RMIConnectorServer.start(RMIConnectorServer.java:405) ~[na:1.8.0_161]
        at org.apache.cassandra.utils.JMXServerUtils.createJMXServer(JMXServerUtils.java:106) ~[apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.CassandraDaemon.maybeInitJmx(CassandraDaemon.java:145) [apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:219) [apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:601) [apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:730) [apache-cassandra-3.9.jar:3.9]
```

**Comment by meatballhat** [comment]
Oh, neat!  https://stackoverflow.com/a/48328792
