### ISSUE TITLE
Unable to build `ci-sardonyx` with docker builder

### ISSUE THREAD

**Issue by blazejpawlak** [travis-ci/packer-templates#687]
I'm trying to build a docker image with `make ci-sardonyx BUILDER=docker` and it first failed with:

```
==> docker: Starting docker container...
    docker: Run command: docker run -v /Users/tetsuo/.packer.d/tmp:/packer-files -d -v /Users/tetsuo/Downloads/packer-templates/tmp/packer-builder-tmp:/tmp --privileged=true --storage-opt=size=15G travisci/gce-parity:16.04 /sbin/init
==> docker: Error running container: Docker exited with a non-zero exit status.
==> docker: Stderr: docker: Error response from daemon: --storage-opt is supported only for overlay over xfs with 'pquota' mount option.
==> docker: See 'docker run --help'.
==> docker:
Build 'docker' errored: Error running container: Docker exited with a non-zero exit status.
Stderr: docker: Error response from daemon: --storage-opt is supported only for overlay over xfs with 'pquota' mount option.
See 'docker run --help'.
```

which I mitigated by removing `--storage-opt=size=15G` from the docker run command. Apparently this could be fixed by adding appropriate entry into the `/etc/default/grub` file as mentioned at [docker forums](https://forums.docker.com/t/storage-quota-per-container-overlay2-backed-by-xfs/37653).

However the processed crashed at trying to reach https://api.github.com/repositories/612230/releases/latest where it cannot fetch a key `tag_name` for the presented json file.

```
    docker: Compiling Cookbooks...
==> docker: /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/packagecloud/resources/repo.rb:10: warning: constant ::Fixnum is deprecated
    docker: ================================================================================
    docker: Recipe Compile Error in /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/travis_ci_sardonyx/recipes/default.rb
    docker: ================================================================================
    docker: KeyError
    docker: --------
    docker: key not found: "tag_name"
    docker: Cookbook Trace:
    docker: ---------------
    docker:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/travis_build_environment/recipes/gimme.rb:36:in `fetch'
    docker:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/travis_build_environment/recipes/gimme.rb:36:in `obtain_gimme_url'
    docker:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/travis_build_environment/recipes/gimme.rb:40:in `from_file'
    docker:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/travis_build_environment/recipes/basic.rb:62:in `from_file'
    docker:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/travis_build_environment/recipes/default.rb:26:in `from_file'
    docker:   /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/travis_ci_sardonyx/recipes/default.rb:29:in `from_file'
    docker: Relevant File Content:
    docker: ----------------------
    docker: /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/travis_build_environment/recipes/gimme.rb:
    docker:  29:    http.use_ssl = true
    docker:  30:    http.verify_mode = OpenSSL::SSL::VERIFY_PEER
    docker:  31:    request = Net::HTTP::Get.new('/repos/travis-ci/gimme/releases/latest')
    docker:  32:    request['Accept'] = 'application/json'
    docker:  33:    token = node&.[]('travis_packer_build')&.[]('github_token')
    docker:  34:    request['Authorization'] = "token #{token}" if token
    docker:  35:    response = http.request(request)
    docker:  36>>   tag = JSON.parse(response.body).fetch('tag_name')
    docker:  37:    "https://raw.githubusercontent.com/travis-ci/gimme/#{tag}/gimme"
    docker:  38:  end
    docker:  39:
    docker:  40:  gimme_url = obtain_gimme_url
    docker:  41:
    docker:  42:  remote_file '/usr/local/bin/gimme' do
    docker:  43:    source gimme_url
    docker:  44:    owner 'root'
    docker:  45:    group 'root'
    docker: System Info:
    docker: ------------
    docker: chef_version=13.8.5
    docker: platform=ubuntu
    docker: platform_version=16.04
    docker: ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
    docker: program_name=chef-solo worker: ppid=1464;start=08:49:32;
    docker: executable=/opt/chef/bin/chef-solo
    docker: Running handlers:
    docker: [2019-04-25T08:50:44+00:00] ERROR: Running exception handlers
    docker: [2019-04-25T08:50:44+00:00] ERROR: Running exception handlers
    docker: Running handlers complete
    docker: [2019-04-25T08:50:44+00:00] ERROR: Exception handlers complete
    docker: [2019-04-25T08:50:44+00:00] ERROR: Exception handlers complete
    docker: Chef Client failed. 0 resources updated in 01 minutes 11 seconds
    docker: [2019-04-25T08:50:44+00:00] FATAL: Stacktrace dumped to /tmp/packer-chef-solo/local-mode-cache/cache/chef-stacktrace.out
    docker: [2019-04-25T08:50:44+00:00] FATAL: Stacktrace dumped to /tmp/packer-chef-solo/local-mode-cache/cache/chef-stacktrace.out
    docker: [2019-04-25T08:50:44+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    docker: [2019-04-25T08:50:44+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    docker: [2019-04-25T08:50:44+00:00] ERROR: key not found: "tag_name"
    docker: [2019-04-25T08:50:44+00:00] ERROR: key not found: "tag_name"
    docker: [2019-04-25T08:50:44+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
    docker: [2019-04-25T08:50:44+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
==> docker: Killing the container: ce0dcdccb861eee2a883f6dfc66dce25d2f9e6987a8e8aa048fcb49c719331b5
Build 'docker' errored: Error executing Chef: Non-zero exit status: 1
```

Is there any way I could mitigate this myself just to try the build process?

**Comment by aTonyXiao** [comment]
I have exactly the same error when build `ci-stevonnie`.

**Comment by aTonyXiao** [comment]
@blazejpawlak I am able to workaround that by commenting out [line 33-34](https://github.com/travis-ci/travis-cookbooks/blob/ac8e239c814f88ae3bd6c191cdfe2930a63b1c15/cookbooks/travis_build_environment/recipes/gimme.rb#L33) and line [36-37](https://github.com/travis-ci/travis-cookbooks/blob/ac8e239c814f88ae3bd6c191cdfe2930a63b1c15/cookbooks/travis_build_environment/recipes/ci_user.rb#L36). 
I forked the cookbooks repo and made above changes. 
Then edited [here](https://github.com/travis-ci/packer-templates/blob/0fce4d520bae75b3cebd928156011bdfc085d6aa/packer-scripts/clone-travis-cookbooks#L17) to : `"${TRAVIS_COOKBOOKS_URL:=https://github.com/aTonyXiao/travis-cookbooks.git}"` so that the packer will download the edited cookbooks.
